### ISSUE TITLE
Add TODO Guides ideas

### ISSUE THREAD

**Issue by anajsana** [todogroup/work-day-activities#19]
## Goal
Improve TODO Guides content

## Description
We had an issue tracking TODO guides ideas in 2020 and I think we can keep the conversation and use them for 202: https://github.com/todogroup/todogroup.org/issues/143

**Closign conditions**
- [ ] Add ideas to the ticket
- [ ] Define guides and Create new issues for each guide
- [ ] Assign contributors
- [ ] Work on the issues from each guide
