### ISSUE TITLE
Checklist for: Reviewing And Updating Policy Examples 

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/work-day-activities#22]
## Goal
Ensure freshness in the https://github.com/todogroup/policies repo

## Description
We need to check the links in the Policies repo occasionally to ensure that they're still live. It's also a good opportunity to add new policy examples that may have been posted since our last Work Day.

## Action Items
 - [ ] Go to the https://github.com/todogroup/policies repository
 - [ ] Click each link listed in the Examples and Templates section
 - [ ] Verify that each link successfully resolves to the stated policy example
 - [ ] Ask the Work Day attendees if they are aware of any newly posted policies
 - [ ] If any broken links or new policies are found, submit a pull request to update or add the relevant links

**Comment by DuaneOBrien** [comment]
Next step for this issue would be to verify the steps and add/amend in the next work day. Once we feel like the checklist is more or less stable and vetted, we should add the checklist as a PR and close this issue.

**Comment by DuaneOBrien** [comment]
When reviewing/testing this checklist, please refer to comments in #9
