### ISSUE TITLE
Checklist for: Reviewing and Updating Awesome OSS Management list

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/work-day-activities#23]
## Goal
Ensure freshness in the https://github.com/todogroup/awesome-ospo repo

## Description
We need to check the links in the Awesome OSS Management list occasionally to ensure that they're still live. It's also a good opportunity to add new tools that may have been released since our last Work Day.

## Action Items

 - [ ] Go to the https://github.com/todogroup/awesome-ospo repository
 - [ ] Verify that each link successfully resolves to the intended target
 - [ ] Ask the Work Day attendees if they are aware of any newly tools
 - [ ] If any broken links or new tools are found, submit a pull request to update or add the relevant links

**Comment by DuaneOBrien** [comment]
Next step for this checklist will be to verify it at the next work day. Once it is stable we should add the checklist to the repo via PR and close this issue.

**Comment by MarkAtwood** [comment]
Fixed a typo, added ScanOSS, link checked other links.

**Comment by ashleywolf** [comment]
Fixed a typo, added MVG, added DCOBot
