### ISSUE TITLE
Create TODO Guides

### ISSUE THREAD

**Issue by Sealjay** [todogroup/work-day-activities#25]
## Goal
Take https://github.com/todogroup/work-day-activities/issues/19 and https://github.com/todogroup/todogroup.org/issues/143 and break it into individual granular issues

## Description
We have an older conversation thread for guides, and it is hard for others to pick up an individual topic

## Action Items

 - [ ] @sealjay Create an issue for each guide idea
 - [ ] @sealjay Reference the previous threads
 - [ ] @anajsana to add a guides tag to the new issues
 - [ ] @anajsana to then close https://github.com/todogroup/work-day-activities/issues/19 and https://github.com/todogroup/todogroup.org/issues/143

**Comment by Sealjay** [comment]
@anajsana could you close https://github.com/todogroup/work-day-activities/issues/19 and https://github.com/todogroup/todogroup.org/issues/143 please?

Would you mind also adding a Guide tag to:
- https://github.com/todogroup/work-day-activities/issues/26
- https://github.com/todogroup/work-day-activities/issues/27
- https://github.com/todogroup/work-day-activities/issues/28
- https://github.com/todogroup/work-day-activities/issues/29
- https://github.com/todogroup/work-day-activities/issues/30
- https://github.com/todogroup/work-day-activities/issues/31
Please :)
